#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NEP")]
	public partial class GenDODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGenerateDO_YikTing(GenerateDO_YikTing instance);
    partial void UpdateGenerateDO_YikTing(GenerateDO_YikTing instance);
    partial void DeleteGenerateDO_YikTing(GenerateDO_YikTing instance);
    #endregion
		
		public GenDODataContext() : 
				base(global::idk.Properties.Settings.Default.NEPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GenDODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenDODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenDODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GenDODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GenerateDO_YikTing> GenerateDO_YikTings
		{
			get
			{
				return this.GetTable<GenerateDO_YikTing>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GenerateDO_YikTing")]
	public partial class GenerateDO_YikTing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SinNo;
		
		private string _TranCode;
		
		private string _Location;
		
		private string _UserID;
		
		private string _Remarks;
		
		private string _GeneratedDO;
		
		private System.Nullable<int> _isgenerate;
		
		private System.Nullable<int> _isconfirm;
		
		private System.Nullable<int> _isposting;
		
		private System.Nullable<int> _deliverycompid;
		
		private string _trackingno;
		
		private string _Notes;
		
		private System.Nullable<int> _isdeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSinNoChanging(string value);
    partial void OnSinNoChanged();
    partial void OnTranCodeChanging(string value);
    partial void OnTranCodeChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnGeneratedDOChanging(string value);
    partial void OnGeneratedDOChanged();
    partial void OnisgenerateChanging(System.Nullable<int> value);
    partial void OnisgenerateChanged();
    partial void OnisconfirmChanging(System.Nullable<int> value);
    partial void OnisconfirmChanged();
    partial void OnispostingChanging(System.Nullable<int> value);
    partial void OnispostingChanged();
    partial void OndeliverycompidChanging(System.Nullable<int> value);
    partial void OndeliverycompidChanged();
    partial void OntrackingnoChanging(string value);
    partial void OntrackingnoChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnisdeletedChanging(System.Nullable<int> value);
    partial void OnisdeletedChanged();
    #endregion
		
		public GenerateDO_YikTing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinNo", DbType="VarChar(300)")]
		public string SinNo
		{
			get
			{
				return this._SinNo;
			}
			set
			{
				if ((this._SinNo != value))
				{
					this.OnSinNoChanging(value);
					this.SendPropertyChanging();
					this._SinNo = value;
					this.SendPropertyChanged("SinNo");
					this.OnSinNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranCode", DbType="VarChar(300)")]
		public string TranCode
		{
			get
			{
				return this._TranCode;
			}
			set
			{
				if ((this._TranCode != value))
				{
					this.OnTranCodeChanging(value);
					this.SendPropertyChanging();
					this._TranCode = value;
					this.SendPropertyChanged("TranCode");
					this.OnTranCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(300)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(300)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(300)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneratedDO", DbType="VarChar(300)")]
		public string GeneratedDO
		{
			get
			{
				return this._GeneratedDO;
			}
			set
			{
				if ((this._GeneratedDO != value))
				{
					this.OnGeneratedDOChanging(value);
					this.SendPropertyChanging();
					this._GeneratedDO = value;
					this.SendPropertyChanged("GeneratedDO");
					this.OnGeneratedDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isgenerate", DbType="Int")]
		public System.Nullable<int> isgenerate
		{
			get
			{
				return this._isgenerate;
			}
			set
			{
				if ((this._isgenerate != value))
				{
					this.OnisgenerateChanging(value);
					this.SendPropertyChanging();
					this._isgenerate = value;
					this.SendPropertyChanged("isgenerate");
					this.OnisgenerateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isconfirm", DbType="Int")]
		public System.Nullable<int> isconfirm
		{
			get
			{
				return this._isconfirm;
			}
			set
			{
				if ((this._isconfirm != value))
				{
					this.OnisconfirmChanging(value);
					this.SendPropertyChanging();
					this._isconfirm = value;
					this.SendPropertyChanged("isconfirm");
					this.OnisconfirmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isposting", DbType="Int")]
		public System.Nullable<int> isposting
		{
			get
			{
				return this._isposting;
			}
			set
			{
				if ((this._isposting != value))
				{
					this.OnispostingChanging(value);
					this.SendPropertyChanging();
					this._isposting = value;
					this.SendPropertyChanged("isposting");
					this.OnispostingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliverycompid", DbType="Int")]
		public System.Nullable<int> deliverycompid
		{
			get
			{
				return this._deliverycompid;
			}
			set
			{
				if ((this._deliverycompid != value))
				{
					this.OndeliverycompidChanging(value);
					this.SendPropertyChanging();
					this._deliverycompid = value;
					this.SendPropertyChanged("deliverycompid");
					this.OndeliverycompidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trackingno", DbType="VarChar(500)")]
		public string trackingno
		{
			get
			{
				return this._trackingno;
			}
			set
			{
				if ((this._trackingno != value))
				{
					this.OntrackingnoChanging(value);
					this.SendPropertyChanging();
					this._trackingno = value;
					this.SendPropertyChanged("trackingno");
					this.OntrackingnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="VarChar(300)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdeleted", DbType="Int")]
		public System.Nullable<int> isdeleted
		{
			get
			{
				return this._isdeleted;
			}
			set
			{
				if ((this._isdeleted != value))
				{
					this.OnisdeletedChanging(value);
					this.SendPropertyChanging();
					this._isdeleted = value;
					this.SendPropertyChanged("isdeleted");
					this.OnisdeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
